name: Approval workflow

on:
  push:
    branches: stable

jobs:
  BASE-STAGING:
    name: Base Staging
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup the Environment
        run: |
            echo Setup Env;

  NZ-STAGING:
    name: NZ Staging
    needs: BASE-STAGING
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup NZ
        run: |
            echo Setup NZ;

  UK-STAGING:
    name: UK Staging
    needs: BASE-STAGING
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup UK
        run: |
            echo Setup UK;

  AUTOMATED-RELEASE:
    name: Automated release
    needs: [BASE-STAGING,NZ-STAGING,UK-STAGING]
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: stable

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          fromTag: ${{ steps.tag_version.outputs.previous_tag }}
          toTag: ${{ steps.tag_version.outputs.new_tag }}
          configuration: "configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release/${{ steps.tag_version.outputs.new_tag }}
          body: ${{steps.github_release.outputs.changelog}}
          draft: false
          prerelease: false

      - name: Changelog update
        uses: rhysd/changelog-from-release/action@v2
        with:
          file: CHANGELOG.md
          github_token: ${{ secrets.GITHUB_TOKEN }}

  BASE:
    name: Base Production
    needs: AUTOMATED-RELEASE
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup the Environment
        run: |
            echo Setup Env;

  NZ:
    name: NZ Production
    needs: BASE
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup NZ
        run: |
            echo Setup NZ production;

  UK:
    name: UK Production
    needs: BASE
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup UK
        run: |
            echo Setup UK;

  CREATE-PR:
    name: Create Pull Request to main
    needs: [UK,NZ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: peter-evans/create-pull-request@v3
        with:
          title: Sync main with stable
          labels: automated
          reviewers: alancoppin
          base: main
          branch: stable
