name: Approval workflow

on:
  workflow_dispatch:

jobs:
  BASE-STAGING:
    name: Base
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup the Environment
        run: |
            echo Setup Env;

  NZ-STAGING:
    name: NZ
    needs: BASE-STAGING
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup NZ
        run: |
            echo Setup NZ;

  UK-STAGING:
    name: UK
    needs: BASE-STAGING
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup UK
        run: |
            echo Setup UK;
        

  production:
    needs: [BASE-STAGING,NZ-STAGING,UK-STAGING]
    name: Deploy to Production
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup Production
        run: |
            echo Setup Production;
        

  
