name: Approval workflow

on:
  workflow_dispatch:

jobs:
  name: Build
  # PR must must be merged, not closed to trigger a deployment
  if: github.event.pull_request.merged
  runs-on: ubuntu-latest
  steps:
    - name: Setup the Environment
        

  staging:
    needs: build
    environment: Deploy to Staging
      name: staging
    runs-on: ubuntu-latest
    steps:
    - name: Staging Env
        

  production:
    needs: staging
    environment: Deploy to Production
      name: production
    runs-on: ubuntu-latest
    steps:
    - name: Production Env
        

  
