name: Approval workflow

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    # PR must must be merged, not closed to trigger a deployment
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'

      - name: Setup the Environment
        run: |
            echo Setup Env;

  staging:
    needs: build
    name: Deploy to Staging
    environment:
      name: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'

      - name: Setup Staging
        run: |
            echo Setup Staging;
        

  production:
    needs: staging
    name: Deploy to Production
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'

      - name: Setup Production
        run: |
            echo Setup Production;
        

  
