name: Approval workflow

on:
  workflow_dispatch:

jobs:
  BASE-STAGING:
    name: Base Staging
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup the Environment
        run: |
            echo Setup Env;

  NZ-STAGING:
    name: NZ Staging
    needs: BASE-STAGING
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup NZ
        run: |
            echo Setup NZ;

  UK-STAGING:
    name: UK Staging
    needs: BASE-STAGING
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup UK
        run: |
            echo Setup UK;

  BASE:
    name: Base Production
    needs: [BASE-STAGING,NZ-STAGING,UK-STAGING]
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup the Environment
        run: |
            echo Setup Env;

  NZ:
    name: NZ Production
    needs: BASE
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup NZ
        run: |
            echo Setup NZ production;

  UK:
    name: UK Production
    needs: BASE
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup UK
        run: |
            echo Setup UK;
        

  
