name: Bump version
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          fromTag: ${{ steps.tag_version.outputs.previous_tag }}
          toTag: ${{ steps.tag_version.outputs.new_tag }}
          configuration: "configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release/${{ steps.tag_version.outputs.new_tag }}
          body: ${{steps.github_release.outputs.changelog}}
          draft: false
          prerelease: false

      - name: Changelog update
        uses: rhysd/changelog-from-release/action@v2
        with:
          file: CHANGELOG.md
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Update manifest.json version
      #   uses: sergeysova/jq-action@v2
      #   with: 
      #     cmd: jq '.version = "${{ steps.tag_version.outputs.new_tag }}"' static/manifest.json > tmp.$$.json && mv tmp.$$.json static/manifest.json

      # - name: Commit files
      #   run: |
      #     git config --local user.email "$GITHUB_EMAIL"
      #     git config --local user.name "$GITHUB_USERNAME"
      #     git commit -m "doc(CHANGELOG): update" -a
      #   env:
      #     GITHUB_USERNAME: alancoppin
      #     GITHUB_EMAIL: alan.coppin@kathmandu.co.nz

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}
