name: create PR

on:
  workflow_dispatch:


jobs:
  CREATE-PR:
    name: Create Pull Request to main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: peter-evans/create-pull-request@v3
        with:
          title: Sync main with stable
          labels: automated
          reviewers: alancoppin
          base: main
          branch: Automated/sync-main-with-stable
          delete-branch: true